name: build-and-publish-multiarch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU (emulation for non-native architectures)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # use secret store

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/${{ github.repository_owner }}/edge-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create SBOM with Syft
        run: |
          syft packages ghcr.io/${{ github.repository_owner }}/edge-app:${{ github.sha }} -o spdx-json > sbom.spdx.json
          gh release create ${{ github.sha }} --notes "SBOM and image" -F sbom.spdx.json

      - name: Sign image with cosign
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          cosign sign --key cosign.key ghcr.io/${{ github.repository_owner }}/edge-app:${{ github.sha }}
          rm cosign.key